using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace TimeZonesLib
{
    public class MyClass
    {
        public string[] TimeZonesEnglish()
        {
            string[] timeZones = new string[]{
                                    "(UTC-12:00) International Date Line West",
                                    "(UTC-11:00) Midway Island, Samoa",
                                    "(UTC-10:00) Hawaii",
                                    "(UTC-09:00) Alaska",
                                    "(UTC-08:00) Tijuana, Baja California",
                                    "(UTC-08:00) Pacific Time (US & Canada)",
                                    "(UTC-07:00) Mountain Time (US & Canada)",
                                    "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
                                    "(UTC-07:00) Arizona",
                                    "(UTC-06:00) Saskatchewan",
                                    "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
                                    "(UTC-06:00) Central Time (US & Canada)",
                                    "(UTC-06:00) Central America",
                                    "(UTC-05:00) Indiana (East)",
                                    "(UTC-05:00) Eastern Time (US & Canada)",
                                    "(UTC-05:00) Bogota, Lima, Quito, Rio Branco",
                                    "(UTC-04:30) Caracas",
                                    "(UTC-04:00) Santiago",
                                    "(UTC-04:00) Manaus",
                                    "(UTC-04:00) La Paz",
                                    "(UTC-04:00) Atlantic Time (Canada)",
                                    "(UTC-03:30) Newfoundland",
                                    "(UTC-03:00) Montevideo",
                                    "(UTC-03:00) Greenland",
                                    "(UTC-03:00) Georgetown",
                                    "(UTC-03:00) Buenos Aires",
                                    "(UTC-03:00) Brasilia",
                                    "(UTC-02:00) Mid-Atlantic",
                                    "(UTC-01:00) Cape Verde Is.",
                                    "(UTC-01:00) Azores",
                                    "(UTC+00:00) Casablanca",
                                    "(UTC+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London",
                                    "(UTC+00:00) Monrovia, Reykjavik",
                                    "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
                                    "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
                                    "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
                                    "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
                                    "(UTC+01:00) West Central Africa",
                                    "(UTC+02:00) Amman",
                                    "(UTC+02:00) Athens, Bucharest, Istanbul",
                                    "(UTC+02:00) Beirut",
                                    "(UTC+02:00) Cairo",
                                    "(UTC+02:00) Harare, Pretoria",
                                    "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
                                    "(UTC+02:00) Jerusalem",
                                    "(UTC+02:00) Minsk",
                                    "(UTC+02:00) Windhoek",
                                    "(UTC+03:00) Baghdad",
                                    "(UTC+03:00) Kuwait, Riyadh",
                                    "(UTC+03:00) Moscow, St. Petersburg, Volgograd",
                                    "(UTC+03:00) Nairobi",
                                    "(UTC+03:00) Tbilisi",
                                    "(UTC+03:30) Tehran",
                                    "(UTC+04:00) Abu Dhabi, Muscat",
                                    "(UTC+04:00) Baku",
                                    "(UTC+04:00) Port Louis",
                                    "(UTC+04:00) Yerevan",
                                    "(UTC+04:30) Kabul",
                                    "(UTC+05:00) Ekaterinburg",
                                    "(UTC+05:00) Islamabad, Karachi",
                                    "(UTC+05:00) Tashkent",
                                    "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
                                    "(UTC+05:30) Sri Jayawardenepura",
                                    "(UTC+05:45) Kathmandu",
                                    "(UTC+06:00) Almaty, Novosibirsk",
                                    "(UTC+06:00) Astana, Dhaka",
                                    "(UTC+06:30) Yangon (Rangoon)",
                                    "(UTC+07:00) Bangkok, Hanoi, Jakarta",
                                    "(UTC+07:00) Krasnoyarsk",
                                    "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
                                    "(UTC+08:00) Irkutsk, Ulaan Bataar",
                                    "(UTC+08:00) Kuala Lumpur, Singapore",
                                    "(UTC+08:00) Perth",
                                    "(UTC+08:00) Taipei",
                                    "(UTC+09:00) Osaka, Sapporo, Tokyo",
                                    "(UTC+09:00) Seoul",
                                    "(UTC+09:00) Yakutsk",
                                    "(UTC+09:30) Adelaide",
                                    "(UTC+09:30) Darwin",
                                    "(UTC+10:00) Brisbane",
                                    "(UTC+10:00) Canberra, Melbourne, Sydney",
                                    "(UTC+10:00) Guam, Port Moresby",
                                    "(UTC+10:00) Hobart",
                                    "(UTC+10:00) Vladivostok",
                                    "(UTC+11:00) Magadan, Solomon Is., New Caledonia",
                                    "(UTC+12:00) Auckland, Wellington",
                                    "(UTC+12:00) Fiji, Kamchatka, Marshall Is.",
                                    "(UTC+13:00) Nuku'alofa" };
            return timeZones;
        }
        public string[] TimeZonesGerman()
        {
            string[] timeZones = new string[]{ 
                                               "(UTC-12:00) Internationale Datumsgrenze (Westen)",
                                               "(UTC-11:00) Koordinierte Weltzeit-11",
                                               "(UTC-10:00) Aleuten-Inseln",
                                               "(UTC-10:00) Hawaii",
                                               "(UTC-09:30) Marquesas-Inseln",
                                               "(UTC-09:00) Alaska",
                                               "(UTC-09:00) Koordinierte Weltzeit-09",
                                               "(UTC-08:00) Koordinierte Weltzeit-08",
                                               "(UTC-08:00) Niederkalifornien",
                                               "(UTC-08:00) Pacific Zeit (USA & Kanada)",
                                               "(UTC-07:00) Arizona",
                                               "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
                                               "(UTC-07:00) Mountain Zeit (USA & Kanada)",
                                               "(UTC-06:00) Central Zeit (USA & Kanada)",
                                               "(UTC-06:00) Guadalajara, Mexiko-Stadt, Monterrey",
                                               "(UTC-06:00) Mittelamerika",
                                               "(UTC-06:00) Osterinsel",
                                               "(UTC-06:00) Saskatchewan",
                                               "(UTC-04:00) Turks- und Caicosinseln",
                                               "(UTC-05:00) Bogotá, Lima, Quito, Rio Branco",
                                               "(UTC-05:00) Chetumal",
                                               "(UTC-05:00) Eastern Zeit (USA & Kanada)",
                                               "(UTC-05:00) Haiti",
                                               "(UTC-05:00) Havanna",
                                               "(UTC-05:00) Indiana (Ost)",
                                               "(UTC-04:00) Asuncion",
                                               "(UTC-04:00) Atlantic (Kanada)",
                                               "(UTC-04:00) Caracas",
                                               "(UTC-04:00) Cuiaba",
                                               "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
                                               "(UTC-04:00) Santiago",
                                               "(UTC-03:30) Neufundland",
                                               "(UTC-03:00) Araguaína",
                                               "(UTC-03:00) Brasilia",
                                               "(UTC-03:00) Buenos Aires",
                                               "(UTC-03:00) Cayenne, Fortaleza",
                                               "(UTC-03:00) Grönland",
                                               "(UTC-03:00) Montevideo",
                                               "(UTC-03:00) Punta Arenas",
                                               "(UTC-03:00) Salvador",
                                               "(UTC-03:00) St. Pierre und Miquelon",
                                               "(UTC-02:00) Koordinierte Weltzeit-02",
                                               "(UTC-02:00) Mittelatlantik - Alt",
                                               "(UTC-01:00) Azoren",
                                               "(UTC-01:00) Cabo Verde",
                                               "(UTC+00:00) Koordinierte Weltzeit",
                                               "(UTC+00:00) Casablanca",
                                               "(UTC+00:00) Dublin, Edinburgh, Lissabon, London",
                                               "(UTC+00:00) Monrovia, Reykjavik",
                                               "(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien",
                                               "(UTC+01:00) Belgrad, Bratislava (Pressburg), Budapest, Ljubljana, Prag",
                                               "(UTC+01:00) Brüssel, Kopenhagen, Madrid, Paris",
                                               "(UTC+01:00) Sao Tome",
                                               "(UTC+01:00) Sarajevo, Skopje, Warschau, Zagreb",
                                               "(UTC+01:00) West-Zentralafrika",
                                               "(UTC+02:00) Amman",
                                               "(UTC+02:00) Athen, Bukarest",
                                               "(UTC+02:00) Beirut",
                                               "(UTC+02:00) Chisinau",
                                               "(UTC+02:00) Damaskus",
                                               "(UTC+02:00) Gaza, Hebron",
                                               "(UTC+02:00) Harare, Pretoria",
                                               "(UTC+02:00) Helsinki, Kiew, Riga, Sofia, Tallinn, Wilna",
                                               "(UTC+02:00) Jerusalem",
                                               "(UTC+02:00) Kairo",
                                               "(UTC+02:00) Kaliningrad",
                                               "(UTC+02:00) Khartum",
                                               "(UTC+02:00) Tripolis",
                                               "(UTC+02:00) Windhuk",
                                               "(UTC+03:00) Bagdad",
                                               "(UTC+03:00) Istanbul",
                                               "(UTC+03:00) Kuwait, Riad",
                                               "(UTC+03:00) Minsk",
                                               "(UTC+03:00) Moskau (Moskwa), St. Petersburg, Wolgograd",
                                               "(UTC+03:00) Nairobi",
                                               "(UTC+03:30) Teheran",
                                               "(UTC+04:00) Abu Dhabi, Muskat",
                                               "(UTC+04:00) Astrachan, Uljanowsk",
                                               "(UTC+04:00) Baku",
                                               "(UTC+04:00) Eriwan",
                                               "(UTC+04:00) Ischewsk, Samara",
                                               "(UTC+04:00) Port Louis",
                                               "(UTC+04:00) Saratov",
                                               "(UTC+04:00) Tiflis",
                                               "(UTC+04:30) Kabul",
                                               "(UTC+05:00) Aschgabat, Taschkent",
                                               "(UTC+05:00) Islamabad, Karatschi",
                                               "(UTC+05:00) Jekaterinburg",
                                               "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
                                               "(UTC+05:30) Sri Jayawardenepura",
                                               "(UTC+05:45) Katmandu",
                                               "(UTC+06:00) Astana",
                                               "(UTC+06:00) Dakka",
                                               "(UTC+06:00) Omsk",
                                               "(UTC+06:30) Yangon (Rangun)",
                                               "(UTC+07:00) Bangkok, Hanoi, Jakarta",
                                               "(UTC+07:00) Barnaul, Gorno-Altaisk",
                                               "(UTC+07:00) Hovd",
                                               "(UTC+07:00) Krasnojarsk",
                                               "(UTC+07:00) Nowosibirsk",
                                               "(UTC+07:00) Tomsk",
                                               "(UTC+08:00) Irkutsk",
                                               "(UTC+08:00) Kuala Lumpur, Singapur",
                                               "(UTC+08:00) Peking, Chongqing, Hongkong (SAR), Urumchi",
                                               "(UTC+08:00) Perth",
                                               "(UTC+08:00) Taipeh",
                                               "(UTC+08:00) Ulan-Bator",
                                               "(UTC+08:30) Pjöngjang",
                                               "(UTC+08:45) Eucla",
                                               "(UTC+09:00) Chita",
                                               "(UTC+09:00) Jakutsk",
                                               "(UTC+09:00) Osaka, Sapporo, Tokio",
                                               "(UTC+09:00) Seoul",
                                               "(UTC+09:30) Adelaide",
                                               "(UTC+09:30) Darwin",
                                               "(UTC+10:00) Brisbane",
                                               "(UTC+10:00) Canberra, Melbourne, Sydney",
                                               "(UTC+10:00) Guam, Port Moresby",
                                               "(UTC+10:00) Hobart",
                                               "(UTC+10:00) Wladiwostok",
                                               "(UTC+10:30) Lord-Howe-Insel",
                                               "(UTC+11:00) Bougainville-Insel",
                                               "(UTC+11:00) Magadan",
                                               "(UTC+11:00) Norfolkinsel",
                                               "(UTC+11:00) Sachalin",
                                               "(UTC+11:00) Salomonen, Neu-Kaledonien",
                                               "(UTC+11:00) Tschokurdach",
                                               "(UTC+12:00) Anadyr, Petropawlowsk-Kamtschatski",
                                               "(UTC+12:00) Auckland, Wellington",
                                               "(UTC+12:00) Fidschi",
                                               "(UTC+12:00) Koordinierte Weltzeit+12",
                                               "(UTC+12:00) Petropawlowsk-Kamtschatski - veraltet",
                                               "(UTC+12:45) Chatham-Inseln",
                                               "(UTC+13:00) Koordinierte Weltzeit+13",
                                               "(UTC+13:00) Nuku'alofa",
                                               "(UTC+13:00) Samoa",
                                               "(UTC+14:00) Insel Kiritimati"};
            return timeZones;
        }
        public string[] TimeZonesArabic()
        {
            string[] timeZones = new string[]{ 
                                               "(UTC-12:00) غرب خط التاريخ الدولي",
                                               "(UTC-11:00) الجزيرة الوسطى، ساموا",
                                               "(UTC-10:00)هاواي",
                                               "(UTC-10:00)ألاسكا",
                                               "(UTC-08:00)(الباسيفيكي تيجوانا (الولايات المتحدة وكندا",
                                               "(UTC-08:00) تيجوانا، باخا كاليفورنيا",
                                               "(UTC-07:00)(الجبلي (الولايات المتحدة وكندا ",
                                               "(UTC-07:00) مازاتلان تشيواوا، لاباز",
                                               "(UTC-07:00) أريزونا",
                                               "(UTC-07:00) تشيواوا، لاباز، مازاتلان-جديد",
                                               "(UTC-06:00)(التوقيت المركزي  (الولايات المتحدة وكندا",
                                               "(UTC-06:00) ساسكاتشوان",
                                               "(UTC-06:00)غوادالاخارا، مكسيكو سيتي، مونتيري",
                                               "(UTC-06:00) أمريكا الوسطى ",
                                               "(UTC-06:00) غوادالاخارا، مكسيكو سيتي، مونتيري-جديد  ",
                                               "(UTC-05:00)(التوقيت الشرقي  (الولايات المتحدة وكندا",
                                               "(UTC-05:00) (إنديانا (شرق",
                                               "(UTC-05:00) بوغوتا، ليما، كيتو",
                                               "(UTC-04:30) كاراكاس ",
                                               "(UTC-04:00) (وقت الأطلنطي (كندا",
                                               "(UTC-04:00) جورج تاون، لاباز، سان خوان",
                                               "(UTC-04:00) سانتياغو",
                                               "(UTC-04:00) أسونسيون",
                                               "(UTC-04:00)ماناوس ",
                                               "(UTC-04:00) بورت لويس",
                                               "(UTC-03:30) نيوفاوندلاند",
                                               "(UTC-03:30)  بوينس آيرس ",
                                               "(UTC-03:00) برازيليا",
                                               "(UTC-03:00) جورج تاون",
                                               "(UTC-03:00) جرين لاند",
                                               "(UTC-03:00) مونتيفيديو",
                                               "(UTC-02:00) وسط الأطلنطي",
                                               "(UTC-01:00) أزورس",
                                               "(UTC-01:00) جزر الرأس الأخضر",
                                               "(UTC+00:00) توقيت جرينتش: دبلن، أدنبرة، لشبونة، لندن",
                                               "(UTC+00:00) التوقيت العالمي",
                                               "(UTC+00:00) مونروفيا، ريكيافيك",
                                               "(UTC+01:00)بلغراد، براتيسلافا، بودابست، ليوبليانا، براغ",
                                               "(UTC+01:00) سراييفو، سكوبي، وارسو، زغرب",
                                               "(UTC+01:00) بروكسل، كوبنهاغن، مدريد، باريس",
                                               "(UTC+01:00) أمستردام، برلين، برن، روما، ستوكهولم، فيينا",
                                               "(UTC+01:00) غرب أفريقيا الوسطى",
                                               "(UTC+02:00) مينسك",
                                               "(UTC+02:00) القاهرة",
                                               "(UTC+02:00) هلسنكي، كييف، ريغا، صوفيا، تالين، فيلنيوس",
                                               "(UTC+02:00) أثينا، بوخارست، اسطنبول",
                                               "(UTC+02:00)القدس",
                                               "(UTC+02:00) ويندهوك",
                                               "(UTC+02:00) بيروت",
                                               "(UTC+02:00) عمان",
                                               "(UTC+02:00) هراري، بريتوريا",
                                               "(UTC+03:00) موسكو، سان بطرسبرغ، فولغوغراد",
                                               "(UTC+03:00) الكويت، الرياض",
                                               "(UTC+03:00) نيروبي",
                                               "(UTC+03:00) بغداد",
                                               "(UTC+03:00) تبليسي",
                                               "(UTC+03:00) بوينس آيرس ",
                                               "(UTC+03:00) طهران",
                                               "(UTC+04:00) أبو ظبي، مسقط",
                                               "(UTC+04:00) بورت لويس ",
                                               "(UTC+04:00) يريفان ",
                                               "(UTC+04:00)باكو، تبليسي، يريفان",
                                               "(UTC+04:30) كابول",
                                               "(UTC+05:00) إكاترينبرج",
                                               "(UTC+05:00) طشقند",
                                               "(UTC+05:00)  إسلام أباد وكراتشي",
                                               "(UTC+05:30) تشيناي، كلكتا، مومباي، الهند",
                                               "(UTC+05:45) كاتماندو",
                                               "(UTC+06:00) أستانا، دكا",
                                               "(UTC+06:00) سري جاياواردينيبورا",
                                               "(UTC+06:00) ألماتي، نوفوسيبيرسك",
                                               "(UTC+06:30) يانجون ",
                                               "(UTC+07:00) بانكوك، هانوي، جاكرتا",
                                               "(UTC+07:00) كراسنويارسك",
                                               "(UTC+08:00) بكين أورومتشي تشونغتشينغ، هونغ كونغ",
                                               "(UTC+08:00) كوالالمبور وسنغافورة",
                                               "(UTC+08:00) تايبيه",
                                               "(UTC+08:00) بيرث",
                                               "(UTC+08:00) إركوتسك، أولان باتار",
                                               "(UTC+09:00) سول",
                                               "(UTC+09:00) طوكيو ",
                                               "(UTC+09:00) ياكوتسك",
                                               "(UTC+09:30) داروين",
                                               "(UTC+09:30) أديليد",
                                               "(UTC+10:00) كانبيرا، ملبورن، سيدني",
                                               "(UTC+10:00) بريزبين",
                                               "(UTC+10:00) هوبارت",
                                               "(UTC+10:00) فلاديفوستوك",
                                               "(UTC+10:00) غوام، بورت مورسبي",
                                               "(UTC+11:00)ماجادان، جزر سليمان، كاليدونيا الجديدة ",
                                               "(UTC+12:00) يتم تنظيم فيجي، كامتشاتكا،.",
                                               "(UTC+12:00) أوكلاند، ولينغتون",
                                               "(UTC+12:00) بتروبافلوفسك-كامتشاتسكي",
                                               "(UTC+13:00)نوكوعلوفا " };
            return timeZones;
        }



    }
}
